xmin_timeframes: [15, 30]

mode_speeds:
  foot-walking: 1.3889  # m/s (5 km/h)
  cycling-regular: 4.1667 # m/s (15 km/h)

hex_resolution: 8 # Set the  H3 resolution. ref: https://h3geo.org/docs/core-library/restable/

poi_setting: 'two_level'